name: Deploy to Prod Instance

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Prod Instance and Update
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_KEY }}
          script: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            
            docker pull ${{ secrets.DOCKER_USERNAME }}/node-sample-app:${{ github.sha }}
            
            docker stop my-app || true
            docker rm my-app || true
            
            # 4. Run the new container
            docker run -d \
              --name my-app \
              -p 8001:5006 \
              --restart always \
              ${{ secrets.DOCKER_USERNAME }}/node-sample-app:${{ github.sha }}
